### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by skorokithakis** [seppo0010/rlite-go#1]
When trying to install with `go get`, I get the following error:

```
02:34:57 $ go get github.com/seppo0010/rlite-go
package github.com/seppo0010/rlite-go: no buildable Go source files in /home/user/Code/Go/src/github.com/seppo0010/rlite-go
```

**Comment by seppo0010** [comment]
Thanks for the report. It should be fixed now. You might need to delete `/home/user/Code/Go/src/github.com/seppo0010/`.
